version: '3'

tasks:
  build:
    cmds:
      - gradle assembleDebug -Pandroid.useAndroidX=true

  run:
    deps:
      - build
    cmds:
      - adb wait-for-device
      - adb install build/outputs/apk/debug/tsumegolet-debug.apk
      - adb shell am start -n com.skdassoc.tsumegolet/.MainActivity

  format:
    cmds:
      - cmd: ktfmt --kotlinlang-style ./build.gradle.kts ./settings.gradle.kts $(find ./src -name "*.kt")
        platforms: [darwin, linux]
      - cmd: powershell -Command "ktfmt --kotlinlang-style ./build.gradle.kts ./settings.gradle.kts (Get-ChildItem -Recurse ./src -Filter *.kt).FullName"
        platforms: [windows]
