version: '3'

tasks:
  build:
    cmds:
      - gradle assembleDebug -Pandroid.useAndroidX=true

  run:
    deps:
      - build
    cmds:
      - adb wait-for-device
      - adb install build/outputs/apk/debug/tsumegolet-debug.apk
      - adb shell am start -n com.skdassoc.tsumegolet/.MainActivity
